require("packer-config")
require("settings")
require("mappings")

require("colors.onedark")
require("lsp-config.language_server")
require("lsp-config.nvim_cmp")

require("configs.toggleterm")
require("configs.nvim_tree")
require("configs.lualine")
require("configs.bufferline")
require("configs.parser")
require("configs.null_ls")
require("configs.autopairs")
require("lsp-config.luasnip")
require("configs.comment")
require("configs.indent")
require("configs.telescope")
-- require("configs.lspsaga")
